-- Create creators schema =====================================================

CREATE SCHEMA IF NOT EXISTS creators;

-- Apify tables ==================================================================

create table creators.apify_datasets (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  function_name text not null,
  target text null,
  dataset_ids jsonb null,
  successful_retrieval boolean null,
  constraint apify_datasets_pkey primary key (id)
) TABLESPACE pg_default;

-- Creator DB table ===========================================================

CREATE TABLE creators.creator_db (
  creator_id integer generated by default as identity not null,
  full_name text not null,
  image_url_cdn text null,
  image_url text null,
  constraint creator_db_pkey primary key (creator_id),
  constraint creator_db_full_name_key unique (full_name)
) TABLESPACE pg_default;

-- Instagram tables =============================================================

CREATE TABLE creators.instagram_account_db (
  account_id bigint not null,
  creator_id bigint not null,
  username text not null,
  account_url text not null,
  active boolean not null default true,
  constraint instagram_account_db_pkey primary key (account_id),
  constraint instagram_account_db_username_key unique (username),
  constraint instagram_account_db_creator_id_fkey foreign KEY (creator_id) references creators.creator_db (creator_id)
) TABLESPACE pg_default;

CREATE TABLE creators.instagram_account_metrics (
  timestamp timestamp with time zone not null default now(),
  account_id bigint not null,
  follower_count integer null,
  post_count integer null,
  constraint instagram_account_metrics_pkey primary key (account_id, "timestamp"),
  constraint instagram_account_metrics_account_id_fkey foreign KEY (account_id) references creators.instagram_account_db (account_id)
) TABLESPACE pg_default;

CREATE TABLE creators.instagram_post_db (
  post_id bigint not null,
  account_id bigint not null,
  created_at timestamp with time zone not null default now(),
  post_caption text null,
  media_type text null,
  image_url text null,
  image_url_cdn text null,
  video_duration real null,
  post_url text not null,
  campaign_id integer null,
  active boolean not null default true,
  constraint instagram_post_db_pkey primary key (post_id),
  constraint instagram_post_db_account_id_fkey foreign KEY (account_id) references creators.instagram_account_db (account_id)
) TABLESPACE pg_default;

CREATE TABLE creators.instagram_post_metrics (
  post_id bigint not null,
  like_count integer null,
  comment_count integer null,
  play_count integer null,
  timestamp timestamp with time zone not null default now(),
  constraint instagram_post_metrics_pkey primary key (post_id, "timestamp"),
  constraint instagram_post_metrics_post_id_fkey foreign KEY (post_id) references creators.instagram_post_db (post_id)
) TABLESPACE pg_default;

-- TikTok tables ===============================================================

CREATE TABLE creators.tiktok_account_db (
  account_id bigint not null,
  creator_id bigint not null,
  username text not null,
  account_url text not null,
  active boolean not null default true,
  constraint tiktok_account_db_pkey primary key (account_id),
  constraint tiktok_account_db_username_key unique (username),
  constraint tiktok_account_db_creator_id_fkey foreign KEY (creator_id) references creators.creator_db (creator_id)
) TABLESPACE pg_default;

CREATE TABLE creators.tiktok_account_metrics (
  account_id bigint not null,
  follower_count integer null,
  post_count integer null,
  timestamp timestamp with time zone not null default now(),
  constraint tiktok_account_metrics_pkey primary key (account_id, "timestamp"),
  constraint tiktok_account_metrics_account_id_fkey foreign KEY (account_id) references creators.tiktok_account_db (account_id)
) TABLESPACE pg_default;

CREATE TABLE creators.tiktok_post_db (
  post_id bigint not null,
  account_id bigint not null,
  created_at timestamp with time zone not null default now(),
  post_caption text null,
  media_type text not null default 'video',
  image_url text null,
  image_url_cdn text null,
  video_duration real null,
  post_url text not null,
  campaign_id integer null,
  active boolean not null default true,
  constraint tiktok_post_db_pkey primary key (post_id),
  constraint tiktok_post_db_account_id_fkey foreign KEY (account_id) references creators.tiktok_account_db (account_id)
) TABLESPACE pg_default;

CREATE TABLE creators.tiktok_post_metrics (
  post_id bigint not null,
  like_count integer null,
  comment_count integer null,
  play_count integer null,
  share_count integer null,
  bookmark_count integer null,
  timestamp timestamp with time zone not null default now(),
  constraint tiktok_post_metrics_pkey primary key (post_id, "timestamp"),
  constraint tiktok_post_metrics_post_id_fkey foreign KEY (post_id) references creators.tiktok_post_db (post_id)
) TABLESPACE pg_default;

-- OnlyFans tables =============================================================

CREATE TABLE creators.onlyfans_account_db (
  account_id integer generated by default as identity not null,
  creator_id bigint not null,
  username text not null,
  active boolean not null default true,
  constraint onlyfans_account_db_pkey primary key (account_id),
  constraint onlyfans_account_db_username_key unique (username),
  constraint onlyfans_account_db_creator_id_fkey foreign KEY (creator_id) references creators.creator_db (creator_id)
) TABLESPACE pg_default;

CREATE TABLE creators.onlyfans_account_metrics (
  account_id integer not null,
  new_subs integer null,
  tips_revenue numeric(10, 2) null,
  message_revenue numeric(10, 2) null,
  subs_revenue numeric(10, 2) null,
  total_revenue numeric(10, 2) null,
  timestamp timestamp with time zone not null default now(),
  constraint onlyfans_account_metrics_pkey primary key (account_id, "timestamp"),
  constraint onlyfans_account_metrics_account_id_fkey foreign KEY (account_id) references creators.onlyfans_account_db (account_id)
) TABLESPACE pg_default;

-- Fanfix tables =================================================================

CREATE TABLE creators.fanfix_account_db (
  account_id integer generated by default as identity not null,
  creator_id bigint not null,
  username text not null,
  active boolean not null default true,
  constraint fanfix_account_db_pkey primary key (account_id),
  constraint fanfix_account_db_username_key unique (username),
  constraint fanfix_account_db_creator_id_fkey foreign KEY (creator_id) references creators.creator_db (creator_id)
) TABLESPACE pg_default;

CREATE TABLE creators.fanfix_account_metrics (
  account_id integer not null,
  page_views integer null,
  tips_revenue numeric(10, 2) null,
  subs_revenue numeric(10, 2) null,
  total_revenue numeric(10, 2) null,
  timestamp timestamp with time zone not null default now(),
  constraint fanfix_account_metrics_pkey primary key (account_id, "timestamp"),
  constraint fanfix_account_metrics_account_id_fkey foreign KEY (account_id) references creators.fanfix_account_db (account_id)
) TABLESPACE pg_default;

