name: Rebase Staging
on: workflow_dispatch

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git fetch origin main staging
          git checkout staging
          git rebase origin/main || exit 1
          git push origin staging --force
