name: Merge Staging to Main
on:
  push:
    branches:
      - staging

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Vercel Check
        uses: louisbrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Vercel/*
          conclusion: success
      - name: Wait for Supabase Check
        uses: louisbrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Supabase/*
          conclusion: success,skipped
      - name: Merge and Sync
        run: |
          git config user.name "GitHub Actions" && git config user.email "actions@github.com" && git checkout main && git merge origin/staging -m "Merge staging to main" && git push origin main && git checkout staging && git merge main && git push origin staging
