name: Auto Merge Staging to Main
on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  merge-staging-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for merging
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Merge staging into main
        run: |
          git checkout main
          git merge origin/staging --no-ff -m "Auto-merge staging into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
